window.KAYLA_OS_SEED = {
  "inventory": [
    {
      "ItemID": "ITEM001",
      "ItemName": "Angus beef burger patties",
      "CategoryID": "CAT001",
      "CategoryName": "Protein",
      "LocationID": "LOC003",
      "LocationName": "Freezer",
      "Quantity": 1,
      "Unit": "box/package",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM002",
      "ItemName": "Boneless pork chops",
      "CategoryID": "CAT001",
      "CategoryName": "Protein",
      "LocationID": "LOC003",
      "LocationName": "Freezer",
      "Quantity": 1,
      "Unit": "package",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM003",
      "ItemName": "Ground pork",
      "CategoryID": "CAT001",
      "CategoryName": "Protein",
      "LocationID": "LOC003",
      "LocationName": "Freezer",
      "Quantity": 1,
      "Unit": "package",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM004",
      "ItemName": "Brussels sprouts",
      "CategoryID": "CAT002",
      "CategoryName": "Frozen Vegetable",
      "LocationID": "LOC003",
      "LocationName": "Freezer",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM005",
      "ItemName": "Mixed vegetables",
      "CategoryID": "CAT002",
      "CategoryName": "Frozen Vegetable",
      "LocationID": "LOC003",
      "LocationName": "Freezer",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": true,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 5,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM006",
      "ItemName": "Garlic toast",
      "CategoryID": "CAT004",
      "CategoryName": "Bread",
      "LocationID": "LOC003",
      "LocationName": "Freezer",
      "Quantity": 1,
      "Unit": "box",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM007",
      "ItemName": "Bacon, egg & cheese breakfast sandwiches",
      "CategoryID": "CAT003",
      "CategoryName": "Frozen Meal",
      "LocationID": "LOC003",
      "LocationName": "Freezer",
      "Quantity": 1,
      "Unit": "box",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM008",
      "ItemName": "Protein smoothie bowls",
      "CategoryID": "CAT009",
      "CategoryName": "Breakfast",
      "LocationID": "LOC003",
      "LocationName": "Freezer",
      "Quantity": 1,
      "Unit": "box/package",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM009",
      "ItemName": "Frozen prepared meals",
      "CategoryID": "CAT003",
      "CategoryName": "Frozen Meal",
      "LocationID": "LOC003",
      "LocationName": "Freezer",
      "Quantity": 1,
      "Unit": "assorted",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": "Several varieties; add individually later",
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM010",
      "ItemName": "Kraft macaroni & cheese",
      "CategoryID": "CAT005",
      "CategoryName": "Grain/Pasta",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "box",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM011",
      "ItemName": "Jasmine rice",
      "CategoryID": "CAT005",
      "CategoryName": "Grain/Pasta",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "box",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": true,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 5,
      "Favorite": false,
      "Active": true,
      "Notes": "Boil-in-bag",
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM012",
      "ItemName": "Zatarain's jambalaya mix",
      "CategoryID": "CAT005",
      "CategoryName": "Grain/Pasta",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "box",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM013",
      "ItemName": "Stuffing mix",
      "CategoryID": "CAT005",
      "CategoryName": "Grain/Pasta",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "box",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM014",
      "ItemName": "Ritz crackers",
      "CategoryID": "CAT010",
      "CategoryName": "Snack",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "box",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM015",
      "ItemName": "Movie theater popcorn",
      "CategoryID": "CAT010",
      "CategoryName": "Snack",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "box",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM016",
      "ItemName": "Buldak spicy ramen",
      "CategoryID": "CAT005",
      "CategoryName": "Grain/Pasta",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "package",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM017",
      "ItemName": "Protein bars",
      "CategoryID": "CAT010",
      "CategoryName": "Snack",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "assorted",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM018",
      "ItemName": "Tomato sauce",
      "CategoryID": "CAT006",
      "CategoryName": "Canned Goods",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "can",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": true,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 5,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM019",
      "ItemName": "Tomato soup",
      "CategoryID": "CAT006",
      "CategoryName": "Canned Goods",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "can",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM020",
      "ItemName": "Cream of chicken soup",
      "CategoryID": "CAT006",
      "CategoryName": "Canned Goods",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "can",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM021",
      "ItemName": "Sweet corn",
      "CategoryID": "CAT006",
      "CategoryName": "Canned Goods",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "can",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM022",
      "ItemName": "Sliced carrots",
      "CategoryID": "CAT006",
      "CategoryName": "Canned Goods",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "can",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM023",
      "ItemName": "Pumpkin puree",
      "CategoryID": "CAT006",
      "CategoryName": "Canned Goods",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 3,
      "Unit": "cans",
      "Status": "Use Soon",
      "UseSoon": true,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": "Multiple cans seen",
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM024",
      "ItemName": "Coconut milk",
      "CategoryID": "CAT006",
      "CategoryName": "Canned Goods",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "can",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM025",
      "ItemName": "Cream of coconut",
      "CategoryID": "CAT006",
      "CategoryName": "Canned Goods",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "can",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM026",
      "ItemName": "Sweetened condensed milk",
      "CategoryID": "CAT006",
      "CategoryName": "Canned Goods",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "can",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM027",
      "ItemName": "Capers",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "jar",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM028",
      "ItemName": "Mayonnaise",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "jar",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": true,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 5,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM029",
      "ItemName": "Olive oil mayonnaise",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "jar",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM030",
      "ItemName": "Ranch dressing",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": true,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 5,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM031",
      "ItemName": "Dijon mustard",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": true,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 5,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM032",
      "ItemName": "Yellow mustard",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": true,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 5,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM033",
      "ItemName": "Ketchup",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": true,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 5,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM034",
      "ItemName": "Worcestershire sauce",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": true,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 5,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM035",
      "ItemName": "Soy sauce",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": true,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 5,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM036",
      "ItemName": "Sesame oil",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM037",
      "ItemName": "Sweet chili sauce",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM038",
      "ItemName": "Honey BBQ sauce",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM039",
      "ItemName": "Balsamic vinegar",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM040",
      "ItemName": "Balsamic glaze",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM041",
      "ItemName": "Greek vinaigrette",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM042",
      "ItemName": "Bread dipping oil",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM043",
      "ItemName": "Malt vinegar",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM044",
      "ItemName": "Lemon juice",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": true,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 5,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM045",
      "ItemName": "Tabasco",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bottle",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM046",
      "ItemName": "Creamy tomatillo salsa",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "jar",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM047",
      "ItemName": "Jalapeños",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "jar",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM048",
      "ItemName": "Pepperoncini",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "jar",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM049",
      "ItemName": "Pickle juice/pickles",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "jar",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM050",
      "ItemName": "Minced garlic",
      "CategoryID": "CAT007",
      "CategoryName": "Condiment/Sauce",
      "LocationID": "LOC002",
      "LocationName": "Refrigerator",
      "Quantity": 1,
      "Unit": "jar",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": true,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 5,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM051",
      "ItemName": "Almond flour",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM052",
      "ItemName": "Cassava flour",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM053",
      "ItemName": "Coconut flour",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM054",
      "ItemName": "Oat flour",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM055",
      "ItemName": "Tapioca flour",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM056",
      "ItemName": "Arrowroot flour",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM057",
      "ItemName": "Rolled oats",
      "CategoryID": "CAT009",
      "CategoryName": "Breakfast",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "container",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": true,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 5,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM058",
      "ItemName": "Apple & almond granola",
      "CategoryID": "CAT009",
      "CategoryName": "Breakfast",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM059",
      "ItemName": "Coconut sugar",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM060",
      "ItemName": "Monk fruit sweetener",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM061",
      "ItemName": "Swerve granular sweetener",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM062",
      "ItemName": "Swerve brown sweetener",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM063",
      "ItemName": "Swerve confectioners sweetener",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM064",
      "ItemName": "Swerve allulose",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM065",
      "ItemName": "Beef gelatin powder",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "container",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM066",
      "ItemName": "Pecan halves",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM067",
      "ItemName": "Chopped pecans",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM068",
      "ItemName": "Medjool dates",
      "CategoryID": "CAT010",
      "CategoryName": "Snack",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "container",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM069",
      "ItemName": "Unsweetened coconut flakes",
      "CategoryID": "CAT008",
      "CategoryName": "Baking",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "bag",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": false,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 3,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    },
    {
      "ItemID": "ITEM070",
      "ItemName": "Peanut butter",
      "CategoryID": "CAT010",
      "CategoryName": "Snack",
      "LocationID": "LOC001",
      "LocationName": "Pantry",
      "Quantity": 1,
      "Unit": "jar",
      "Status": "In Stock",
      "UseSoon": false,
      "CoreStaple": true,
      "Opened": null,
      "ExpirationDate": null,
      "PurchaseDate": null,
      "MinimumStock": 0,
      "Barcode": null,
      "PhotoURL": null,
      "VersatilityScore": 5,
      "Favorite": false,
      "Active": true,
      "Notes": null,
      "LastUpdated": "2026-08-02T00:00:00"
    }
  ],
  "recipes": [
    {
      "RecipeID": "REC001",
      "RecipeName": "Ground Pork Fried Rice",
      "MealType": "Dinner",
      "FlavorID": "FLV002",
      "FlavorName": "Asian",
      "MainProtein": "Ground pork",
      "PrepMinutes": 5,
      "CookMinutes": 15,
      "TotalMinutes": 20,
      "Difficulty": "Easy",
      "NoShop": true,
      "HighProtein": true,
      "ComfortFood": false,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Brown pork with garlic. Add vegetables. Stir in cooked rice, soy sauce, and a small amount of sesame oil.",
      "Notes": null,
      "Active": true
    },
    {
      "RecipeID": "REC002",
      "RecipeName": "Sweet Chili Pork Ramen",
      "MealType": "Dinner",
      "FlavorID": "FLV002",
      "FlavorName": "Asian",
      "MainProtein": "Ground pork",
      "PrepMinutes": 5,
      "CookMinutes": 10,
      "TotalMinutes": 15,
      "Difficulty": "Very Easy",
      "NoShop": true,
      "HighProtein": true,
      "ComfortFood": true,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Cook ramen. Brown pork, add vegetables and sauces, then toss with noodles.",
      "Notes": null,
      "Active": true
    },
    {
      "RecipeID": "REC003",
      "RecipeName": "Jambalaya with Ground Pork",
      "MealType": "Dinner",
      "FlavorID": "FLV004",
      "FlavorName": "Cajun",
      "MainProtein": "Ground pork",
      "PrepMinutes": 5,
      "CookMinutes": 25,
      "TotalMinutes": 30,
      "Difficulty": "Easy",
      "NoShop": true,
      "HighProtein": true,
      "ComfortFood": true,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Brown pork, then prepare jambalaya mix according to package directions using the pork.",
      "Notes": null,
      "Active": true
    },
    {
      "RecipeID": "REC004",
      "RecipeName": "Honey BBQ Pork Chops",
      "MealType": "Dinner",
      "FlavorID": "FLV003",
      "FlavorName": "BBQ",
      "MainProtein": "Boneless pork chops",
      "PrepMinutes": 5,
      "CookMinutes": 20,
      "TotalMinutes": 25,
      "Difficulty": "Easy",
      "NoShop": true,
      "HighProtein": true,
      "ComfortFood": true,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Season and sear pork chops. Brush with BBQ sauce and finish cooking. Serve with sprouts and rice.",
      "Notes": null,
      "Active": true
    },
    {
      "RecipeID": "REC005",
      "RecipeName": "Sweet Chili Soy Pork Chops",
      "MealType": "Dinner",
      "FlavorID": "FLV002",
      "FlavorName": "Asian",
      "MainProtein": "Boneless pork chops",
      "PrepMinutes": 5,
      "CookMinutes": 20,
      "TotalMinutes": 25,
      "Difficulty": "Easy",
      "NoShop": true,
      "HighProtein": true,
      "ComfortFood": false,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Mix sauce ingredients, sear chops, add sauce, and simmer until cooked through.",
      "Notes": null,
      "Active": true
    },
    {
      "RecipeID": "REC006",
      "RecipeName": "Greek-Style Pork Chops",
      "MealType": "Dinner",
      "FlavorID": "FLV006",
      "FlavorName": "Mediterranean",
      "MainProtein": "Boneless pork chops",
      "PrepMinutes": 10,
      "CookMinutes": 15,
      "TotalMinutes": 25,
      "Difficulty": "Easy",
      "NoShop": true,
      "HighProtein": true,
      "ComfortFood": false,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Marinate briefly in vinaigrette, lemon, and garlic, then pan-sear or bake.",
      "Notes": null,
      "Active": true
    },
    {
      "RecipeID": "REC007",
      "RecipeName": "Garlic Toast Burgers",
      "MealType": "Dinner",
      "FlavorID": "FLV001",
      "FlavorName": "American",
      "MainProtein": "Angus beef burger patties",
      "PrepMinutes": 5,
      "CookMinutes": 15,
      "TotalMinutes": 20,
      "Difficulty": "Very Easy",
      "NoShop": true,
      "HighProtein": true,
      "ComfortFood": true,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Cook burgers and use garlic toast as the bun. Add preferred condiments.",
      "Notes": null,
      "Active": true
    },
    {
      "RecipeID": "REC008",
      "RecipeName": "Tomato Soup & Garlic Toast",
      "MealType": "Lunch",
      "FlavorID": "FLV005",
      "FlavorName": "Comfort Food",
      "MainProtein": null,
      "PrepMinutes": 2,
      "CookMinutes": 10,
      "TotalMinutes": 12,
      "Difficulty": "Very Easy",
      "NoShop": true,
      "HighProtein": false,
      "ComfortFood": true,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Heat soup and bake garlic toast.",
      "Notes": null,
      "Active": true
    },
    {
      "RecipeID": "REC009",
      "RecipeName": "Creamy Pork & Vegetable Rice",
      "MealType": "Dinner",
      "FlavorID": "FLV005",
      "FlavorName": "Comfort Food",
      "MainProtein": "Ground pork",
      "PrepMinutes": 5,
      "CookMinutes": 20,
      "TotalMinutes": 25,
      "Difficulty": "Easy",
      "NoShop": true,
      "HighProtein": true,
      "ComfortFood": true,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Brown pork. Stir in soup, vegetables, and corn. Serve over rice.",
      "Notes": null,
      "Active": true
    },
    {
      "RecipeID": "REC010",
      "RecipeName": "Pork Stuffing Casserole",
      "MealType": "Dinner",
      "FlavorID": "FLV007",
      "FlavorName": "Southern",
      "MainProtein": "Ground pork",
      "PrepMinutes": 10,
      "CookMinutes": 25,
      "TotalMinutes": 35,
      "Difficulty": "Easy",
      "NoShop": true,
      "HighProtein": true,
      "ComfortFood": true,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Brown pork, combine with soup and vegetables, top with prepared stuffing, and bake.",
      "Notes": null,
      "Active": true
    },
    {
      "RecipeID": "REC011",
      "RecipeName": "BBQ Jalapeño Mac & Cheese",
      "MealType": "Dinner",
      "FlavorID": "FLV005",
      "FlavorName": "Comfort Food",
      "MainProtein": "Ground pork",
      "PrepMinutes": 5,
      "CookMinutes": 15,
      "TotalMinutes": 20,
      "Difficulty": "Easy",
      "NoShop": true,
      "HighProtein": true,
      "ComfortFood": true,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Prepare mac and cheese. Stir in browned pork and jalapeños; drizzle with BBQ sauce.",
      "Notes": null,
      "Active": true
    },
    {
      "RecipeID": "REC012",
      "RecipeName": "Coconut Sweet Chili Pork Bowl",
      "MealType": "Dinner",
      "FlavorID": "FLV008",
      "FlavorName": "Fusion",
      "MainProtein": "Ground pork",
      "PrepMinutes": 5,
      "CookMinutes": 20,
      "TotalMinutes": 25,
      "Difficulty": "Easy",
      "NoShop": true,
      "HighProtein": true,
      "ComfortFood": false,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Brown pork, add vegetables and coconut sauce, simmer, and serve over rice.",
      "Notes": null,
      "Active": true
    },
    {
      "RecipeID": "REC013",
      "RecipeName": "Pumpkin Pecan Oatmeal",
      "MealType": "Breakfast",
      "FlavorID": "FLV009",
      "FlavorName": "Breakfast",
      "MainProtein": null,
      "PrepMinutes": 3,
      "CookMinutes": 7,
      "TotalMinutes": 10,
      "Difficulty": "Very Easy",
      "NoShop": false,
      "HighProtein": false,
      "ComfortFood": true,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Cook oats, stir in pumpkin and sweetener, and top with pecans.",
      "Notes": null,
      "Active": true
    },
    {
      "RecipeID": "REC014",
      "RecipeName": "Peanut Butter Date Bites",
      "MealType": "Snack",
      "FlavorID": "FLV010",
      "FlavorName": "No-Bake",
      "MainProtein": null,
      "PrepMinutes": 10,
      "CookMinutes": 5,
      "TotalMinutes": 15,
      "Difficulty": "Very Easy",
      "NoShop": true,
      "HighProtein": false,
      "ComfortFood": false,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Stuff dates with peanut butter and roll or top with coconut and pecans.",
      "Notes": null,
      "Active": true
    },
    {
      "RecipeID": "REC015",
      "RecipeName": "Pumpkin Energy Bites",
      "MealType": "Snack",
      "FlavorID": "FLV010",
      "FlavorName": "No-Bake",
      "MainProtein": null,
      "PrepMinutes": 10,
      "CookMinutes": 5,
      "TotalMinutes": 15,
      "Difficulty": "Very Easy",
      "NoShop": false,
      "HighProtein": false,
      "ComfortFood": false,
      "KidFriendly": true,
      "Favorite": false,
      "PhotoURL": null,
      "Instructions": "Mix, chill, and roll into bite-sized balls.",
      "Notes": null,
      "Active": true
    }
  ],
  "recipeIngredients": [
    {
      "RecipeIngredientID": "RI0001",
      "RecipeID": "REC001",
      "RecipeName": "Ground Pork Fried Rice",
      "ItemID": "ITEM003",
      "ItemName": "Ground pork",
      "QuantityNeeded": 1,
      "Unit": "package",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0002",
      "RecipeID": "REC001",
      "RecipeName": "Ground Pork Fried Rice",
      "ItemID": "ITEM011",
      "ItemName": "Jasmine rice",
      "QuantityNeeded": 1,
      "Unit": "bag",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0003",
      "RecipeID": "REC001",
      "RecipeName": "Ground Pork Fried Rice",
      "ItemID": "ITEM005",
      "ItemName": "Mixed vegetables",
      "QuantityNeeded": 1,
      "Unit": "cup",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0004",
      "RecipeID": "REC001",
      "RecipeName": "Ground Pork Fried Rice",
      "ItemID": "ITEM035",
      "ItemName": "Soy sauce",
      "QuantityNeeded": 2,
      "Unit": "tbsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0005",
      "RecipeID": "REC001",
      "RecipeName": "Ground Pork Fried Rice",
      "ItemID": "ITEM036",
      "ItemName": "Sesame oil",
      "QuantityNeeded": 1,
      "Unit": "tsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0006",
      "RecipeID": "REC001",
      "RecipeName": "Ground Pork Fried Rice",
      "ItemID": "ITEM050",
      "ItemName": "Minced garlic",
      "QuantityNeeded": 1,
      "Unit": "tsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0007",
      "RecipeID": "REC002",
      "RecipeName": "Sweet Chili Pork Ramen",
      "ItemID": "ITEM003",
      "ItemName": "Ground pork",
      "QuantityNeeded": 0.5,
      "Unit": "package",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0008",
      "RecipeID": "REC002",
      "RecipeName": "Sweet Chili Pork Ramen",
      "ItemID": "ITEM016",
      "ItemName": "Buldak spicy ramen",
      "QuantityNeeded": 1,
      "Unit": "package",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0009",
      "RecipeID": "REC002",
      "RecipeName": "Sweet Chili Pork Ramen",
      "ItemID": "ITEM005",
      "ItemName": "Mixed vegetables",
      "QuantityNeeded": 1,
      "Unit": "cup",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0010",
      "RecipeID": "REC002",
      "RecipeName": "Sweet Chili Pork Ramen",
      "ItemID": "ITEM037",
      "ItemName": "Sweet chili sauce",
      "QuantityNeeded": 1,
      "Unit": "tbsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0011",
      "RecipeID": "REC002",
      "RecipeName": "Sweet Chili Pork Ramen",
      "ItemID": "ITEM035",
      "ItemName": "Soy sauce",
      "QuantityNeeded": 1,
      "Unit": "tbsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0012",
      "RecipeID": "REC003",
      "RecipeName": "Jambalaya with Ground Pork",
      "ItemID": "ITEM003",
      "ItemName": "Ground pork",
      "QuantityNeeded": 1,
      "Unit": "package",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0013",
      "RecipeID": "REC003",
      "RecipeName": "Jambalaya with Ground Pork",
      "ItemID": "ITEM012",
      "ItemName": "Zatarain's jambalaya mix",
      "QuantityNeeded": 1,
      "Unit": "box",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0014",
      "RecipeID": "REC004",
      "RecipeName": "Honey BBQ Pork Chops",
      "ItemID": "ITEM002",
      "ItemName": "Boneless pork chops",
      "QuantityNeeded": 1,
      "Unit": "package",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0015",
      "RecipeID": "REC004",
      "RecipeName": "Honey BBQ Pork Chops",
      "ItemID": "ITEM038",
      "ItemName": "Honey BBQ sauce",
      "QuantityNeeded": 0.25,
      "Unit": "cup",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0016",
      "RecipeID": "REC004",
      "RecipeName": "Honey BBQ Pork Chops",
      "ItemID": "ITEM004",
      "ItemName": "Brussels sprouts",
      "QuantityNeeded": 1,
      "Unit": "bag",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0017",
      "RecipeID": "REC004",
      "RecipeName": "Honey BBQ Pork Chops",
      "ItemID": "ITEM011",
      "ItemName": "Jasmine rice",
      "QuantityNeeded": 1,
      "Unit": "bag",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0018",
      "RecipeID": "REC005",
      "RecipeName": "Sweet Chili Soy Pork Chops",
      "ItemID": "ITEM002",
      "ItemName": "Boneless pork chops",
      "QuantityNeeded": 1,
      "Unit": "package",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0019",
      "RecipeID": "REC005",
      "RecipeName": "Sweet Chili Soy Pork Chops",
      "ItemID": "ITEM037",
      "ItemName": "Sweet chili sauce",
      "QuantityNeeded": 2,
      "Unit": "tbsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0020",
      "RecipeID": "REC005",
      "RecipeName": "Sweet Chili Soy Pork Chops",
      "ItemID": "ITEM035",
      "ItemName": "Soy sauce",
      "QuantityNeeded": 1,
      "Unit": "tbsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0021",
      "RecipeID": "REC005",
      "RecipeName": "Sweet Chili Soy Pork Chops",
      "ItemID": "ITEM036",
      "ItemName": "Sesame oil",
      "QuantityNeeded": 1,
      "Unit": "tsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0022",
      "RecipeID": "REC005",
      "RecipeName": "Sweet Chili Soy Pork Chops",
      "ItemID": "ITEM050",
      "ItemName": "Minced garlic",
      "QuantityNeeded": 1,
      "Unit": "tsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0023",
      "RecipeID": "REC006",
      "RecipeName": "Greek-Style Pork Chops",
      "ItemID": "ITEM002",
      "ItemName": "Boneless pork chops",
      "QuantityNeeded": 1,
      "Unit": "package",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0024",
      "RecipeID": "REC006",
      "RecipeName": "Greek-Style Pork Chops",
      "ItemID": "ITEM041",
      "ItemName": "Greek vinaigrette",
      "QuantityNeeded": 0.25,
      "Unit": "cup",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0025",
      "RecipeID": "REC006",
      "RecipeName": "Greek-Style Pork Chops",
      "ItemID": "ITEM044",
      "ItemName": "Lemon juice",
      "QuantityNeeded": 1,
      "Unit": "tbsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0026",
      "RecipeID": "REC006",
      "RecipeName": "Greek-Style Pork Chops",
      "ItemID": "ITEM050",
      "ItemName": "Minced garlic",
      "QuantityNeeded": 1,
      "Unit": "tsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0027",
      "RecipeID": "REC007",
      "RecipeName": "Garlic Toast Burgers",
      "ItemID": "ITEM001",
      "ItemName": "Angus beef burger patties",
      "QuantityNeeded": 2,
      "Unit": "patties",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0028",
      "RecipeID": "REC007",
      "RecipeName": "Garlic Toast Burgers",
      "ItemID": "ITEM006",
      "ItemName": "Garlic toast",
      "QuantityNeeded": 4,
      "Unit": "slices",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0029",
      "RecipeID": "REC007",
      "RecipeName": "Garlic Toast Burgers",
      "ItemID": "ITEM033",
      "ItemName": "Ketchup",
      "QuantityNeeded": 1,
      "Unit": "tbsp",
      "Optional": true,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0030",
      "RecipeID": "REC007",
      "RecipeName": "Garlic Toast Burgers",
      "ItemID": "ITEM032",
      "ItemName": "Yellow mustard",
      "QuantityNeeded": 1,
      "Unit": "tbsp",
      "Optional": true,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0031",
      "RecipeID": "REC007",
      "RecipeName": "Garlic Toast Burgers",
      "ItemID": "ITEM028",
      "ItemName": "Mayonnaise",
      "QuantityNeeded": 1,
      "Unit": "tbsp",
      "Optional": true,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0032",
      "RecipeID": "REC007",
      "RecipeName": "Garlic Toast Burgers",
      "ItemID": "ITEM047",
      "ItemName": "Jalapeños",
      "QuantityNeeded": 2,
      "Unit": "tbsp",
      "Optional": true,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0033",
      "RecipeID": "REC008",
      "RecipeName": "Tomato Soup & Garlic Toast",
      "ItemID": "ITEM019",
      "ItemName": "Tomato soup",
      "QuantityNeeded": 1,
      "Unit": "can",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0034",
      "RecipeID": "REC008",
      "RecipeName": "Tomato Soup & Garlic Toast",
      "ItemID": "ITEM006",
      "ItemName": "Garlic toast",
      "QuantityNeeded": 2,
      "Unit": "slices",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0035",
      "RecipeID": "REC009",
      "RecipeName": "Creamy Pork & Vegetable Rice",
      "ItemID": "ITEM003",
      "ItemName": "Ground pork",
      "QuantityNeeded": 1,
      "Unit": "package",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0036",
      "RecipeID": "REC009",
      "RecipeName": "Creamy Pork & Vegetable Rice",
      "ItemID": "ITEM011",
      "ItemName": "Jasmine rice",
      "QuantityNeeded": 1,
      "Unit": "bag",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0037",
      "RecipeID": "REC009",
      "RecipeName": "Creamy Pork & Vegetable Rice",
      "ItemID": "ITEM020",
      "ItemName": "Cream of chicken soup",
      "QuantityNeeded": 1,
      "Unit": "can",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0038",
      "RecipeID": "REC009",
      "RecipeName": "Creamy Pork & Vegetable Rice",
      "ItemID": "ITEM005",
      "ItemName": "Mixed vegetables",
      "QuantityNeeded": 1,
      "Unit": "cup",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0039",
      "RecipeID": "REC009",
      "RecipeName": "Creamy Pork & Vegetable Rice",
      "ItemID": "ITEM021",
      "ItemName": "Sweet corn",
      "QuantityNeeded": 1,
      "Unit": "can",
      "Optional": true,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0040",
      "RecipeID": "REC010",
      "RecipeName": "Pork Stuffing Casserole",
      "ItemID": "ITEM003",
      "ItemName": "Ground pork",
      "QuantityNeeded": 1,
      "Unit": "package",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0041",
      "RecipeID": "REC010",
      "RecipeName": "Pork Stuffing Casserole",
      "ItemID": "ITEM013",
      "ItemName": "Stuffing mix",
      "QuantityNeeded": 1,
      "Unit": "box",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0042",
      "RecipeID": "REC010",
      "RecipeName": "Pork Stuffing Casserole",
      "ItemID": "ITEM020",
      "ItemName": "Cream of chicken soup",
      "QuantityNeeded": 1,
      "Unit": "can",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0043",
      "RecipeID": "REC010",
      "RecipeName": "Pork Stuffing Casserole",
      "ItemID": "ITEM005",
      "ItemName": "Mixed vegetables",
      "QuantityNeeded": 1,
      "Unit": "cup",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0044",
      "RecipeID": "REC011",
      "RecipeName": "BBQ Jalapeño Mac & Cheese",
      "ItemID": "ITEM010",
      "ItemName": "Kraft macaroni & cheese",
      "QuantityNeeded": 1,
      "Unit": "box",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0045",
      "RecipeID": "REC011",
      "RecipeName": "BBQ Jalapeño Mac & Cheese",
      "ItemID": "ITEM003",
      "ItemName": "Ground pork",
      "QuantityNeeded": 0.5,
      "Unit": "package",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0046",
      "RecipeID": "REC011",
      "RecipeName": "BBQ Jalapeño Mac & Cheese",
      "ItemID": "ITEM038",
      "ItemName": "Honey BBQ sauce",
      "QuantityNeeded": 2,
      "Unit": "tbsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0047",
      "RecipeID": "REC011",
      "RecipeName": "BBQ Jalapeño Mac & Cheese",
      "ItemID": "ITEM047",
      "ItemName": "Jalapeños",
      "QuantityNeeded": 2,
      "Unit": "tbsp",
      "Optional": true,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0048",
      "RecipeID": "REC012",
      "RecipeName": "Coconut Sweet Chili Pork Bowl",
      "ItemID": "ITEM003",
      "ItemName": "Ground pork",
      "QuantityNeeded": 1,
      "Unit": "package",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0049",
      "RecipeID": "REC012",
      "RecipeName": "Coconut Sweet Chili Pork Bowl",
      "ItemID": "ITEM024",
      "ItemName": "Coconut milk",
      "QuantityNeeded": 1,
      "Unit": "can",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0050",
      "RecipeID": "REC012",
      "RecipeName": "Coconut Sweet Chili Pork Bowl",
      "ItemID": "ITEM037",
      "ItemName": "Sweet chili sauce",
      "QuantityNeeded": 2,
      "Unit": "tbsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0051",
      "RecipeID": "REC012",
      "RecipeName": "Coconut Sweet Chili Pork Bowl",
      "ItemID": "ITEM035",
      "ItemName": "Soy sauce",
      "QuantityNeeded": 1,
      "Unit": "tbsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0052",
      "RecipeID": "REC012",
      "RecipeName": "Coconut Sweet Chili Pork Bowl",
      "ItemID": "ITEM005",
      "ItemName": "Mixed vegetables",
      "QuantityNeeded": 1,
      "Unit": "cup",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0053",
      "RecipeID": "REC012",
      "RecipeName": "Coconut Sweet Chili Pork Bowl",
      "ItemID": "ITEM011",
      "ItemName": "Jasmine rice",
      "QuantityNeeded": 1,
      "Unit": "bag",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0054",
      "RecipeID": "REC013",
      "RecipeName": "Pumpkin Pecan Oatmeal",
      "ItemID": "ITEM057",
      "ItemName": "Rolled oats",
      "QuantityNeeded": 0.5,
      "Unit": "cup",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0055",
      "RecipeID": "REC013",
      "RecipeName": "Pumpkin Pecan Oatmeal",
      "ItemID": "ITEM023",
      "ItemName": "Pumpkin puree",
      "QuantityNeeded": 0.25,
      "Unit": "cup",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0056",
      "RecipeID": "REC013",
      "RecipeName": "Pumpkin Pecan Oatmeal",
      "ItemID": "ITEM066",
      "ItemName": "Pecan halves",
      "QuantityNeeded": 2,
      "Unit": "tbsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0057",
      "RecipeID": "REC013",
      "RecipeName": "Pumpkin Pecan Oatmeal",
      "ItemID": "ITEM059",
      "ItemName": "Coconut sugar",
      "QuantityNeeded": 1,
      "Unit": "tbsp",
      "Optional": true,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0058",
      "RecipeID": "REC014",
      "RecipeName": "Peanut Butter Date Bites",
      "ItemID": "ITEM068",
      "ItemName": "Medjool dates",
      "QuantityNeeded": 6,
      "Unit": "dates",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0059",
      "RecipeID": "REC014",
      "RecipeName": "Peanut Butter Date Bites",
      "ItemID": "ITEM070",
      "ItemName": "Peanut butter",
      "QuantityNeeded": 3,
      "Unit": "tbsp",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0060",
      "RecipeID": "REC014",
      "RecipeName": "Peanut Butter Date Bites",
      "ItemID": "ITEM069",
      "ItemName": "Unsweetened coconut flakes",
      "QuantityNeeded": 2,
      "Unit": "tbsp",
      "Optional": true,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0061",
      "RecipeID": "REC014",
      "RecipeName": "Peanut Butter Date Bites",
      "ItemID": "ITEM067",
      "ItemName": "Chopped pecans",
      "QuantityNeeded": 2,
      "Unit": "tbsp",
      "Optional": true,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0062",
      "RecipeID": "REC015",
      "RecipeName": "Pumpkin Energy Bites",
      "ItemID": "ITEM023",
      "ItemName": "Pumpkin puree",
      "QuantityNeeded": 0.5,
      "Unit": "cup",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0063",
      "RecipeID": "REC015",
      "RecipeName": "Pumpkin Energy Bites",
      "ItemID": "ITEM057",
      "ItemName": "Rolled oats",
      "QuantityNeeded": 1,
      "Unit": "cup",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0064",
      "RecipeID": "REC015",
      "RecipeName": "Pumpkin Energy Bites",
      "ItemID": "ITEM070",
      "ItemName": "Peanut butter",
      "QuantityNeeded": 0.5,
      "Unit": "cup",
      "Optional": false,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0065",
      "RecipeID": "REC015",
      "RecipeName": "Pumpkin Energy Bites",
      "ItemID": "ITEM069",
      "ItemName": "Unsweetened coconut flakes",
      "QuantityNeeded": 0.25,
      "Unit": "cup",
      "Optional": true,
      "InPantry": true,
      "Notes": null
    },
    {
      "RecipeIngredientID": "RI0066",
      "RecipeID": "REC015",
      "RecipeName": "Pumpkin Energy Bites",
      "ItemID": "ITEM067",
      "ItemName": "Chopped pecans",
      "QuantityNeeded": 0.25,
      "Unit": "cup",
      "Optional": true,
      "InPantry": true,
      "Notes": null
    }
  ],
  "shopping": [
    {
      "ShoppingID": "SHOP001",
      "ItemID": null,
      "ItemName": "Eggs",
      "CategoryID": "CAT001",
      "QuantityNeeded": 12,
      "Unit": "count",
      "Priority": "High",
      "Reason": "Fried rice, baking, breakfast, meatballs",
      "EstimatedPrice": null,
      "Purchased": false,
      "Store": null,
      "Notes": null
    },
    {
      "ShoppingID": "SHOP002",
      "ItemID": null,
      "ItemName": "Butter",
      "CategoryID": "CAT014",
      "QuantityNeeded": 1,
      "Unit": "package",
      "Priority": "High",
      "Reason": "Mac & cheese, stuffing, baking",
      "EstimatedPrice": null,
      "Purchased": false,
      "Store": null,
      "Notes": null
    },
    {
      "ShoppingID": "SHOP003",
      "ItemID": null,
      "ItemName": "Milk",
      "CategoryID": "CAT014",
      "QuantityNeeded": 1,
      "Unit": "gallon or half-gallon",
      "Priority": "High",
      "Reason": "Breakfast, casseroles, baking",
      "EstimatedPrice": null,
      "Purchased": false,
      "Store": null,
      "Notes": null
    },
    {
      "ShoppingID": "SHOP004",
      "ItemID": null,
      "ItemName": "Shredded cheese",
      "CategoryID": "CAT014",
      "QuantityNeeded": 1,
      "Unit": "bag",
      "Priority": "High",
      "Reason": "Burgers, mac & cheese, casseroles",
      "EstimatedPrice": null,
      "Purchased": false,
      "Store": null,
      "Notes": null
    },
    {
      "ShoppingID": "SHOP005",
      "ItemID": null,
      "ItemName": "Onions",
      "CategoryID": "CAT013",
      "QuantityNeeded": 3,
      "Unit": "count",
      "Priority": "High",
      "Reason": "Jambalaya, pork, burgers, casseroles",
      "EstimatedPrice": null,
      "Purchased": false,
      "Store": null,
      "Notes": null
    },
    {
      "ShoppingID": "SHOP006",
      "ItemID": null,
      "ItemName": "Bell peppers",
      "CategoryID": "CAT013",
      "QuantityNeeded": 3,
      "Unit": "count",
      "Priority": "Medium",
      "Reason": "Jambalaya, rice bowls, pork",
      "EstimatedPrice": null,
      "Purchased": false,
      "Store": null,
      "Notes": null
    },
    {
      "ShoppingID": "SHOP007",
      "ItemID": null,
      "ItemName": "Fresh fruit",
      "CategoryID": "CAT013",
      "QuantityNeeded": 1,
      "Unit": "selection",
      "Priority": "Medium",
      "Reason": "Breakfasts and snacks",
      "EstimatedPrice": null,
      "Purchased": false,
      "Store": null,
      "Notes": null
    },
    {
      "ShoppingID": "SHOP008",
      "ItemID": null,
      "ItemName": "Salad greens",
      "CategoryID": "CAT013",
      "QuantityNeeded": 1,
      "Unit": "bag",
      "Priority": "Medium",
      "Reason": "Sides and lunches",
      "EstimatedPrice": null,
      "Purchased": false,
      "Store": null,
      "Notes": null
    },
    {
      "ShoppingID": "SHOP009",
      "ItemID": null,
      "ItemName": "Burger buns",
      "CategoryID": "CAT004",
      "QuantityNeeded": 1,
      "Unit": "package",
      "Priority": "Low",
      "Reason": "Standard burgers",
      "EstimatedPrice": null,
      "Purchased": false,
      "Store": null,
      "Notes": null
    },
    {
      "ShoppingID": "SHOP010",
      "ItemID": null,
      "ItemName": "Tortillas",
      "CategoryID": "CAT005",
      "QuantityNeeded": 1,
      "Unit": "package",
      "Priority": "Medium",
      "Reason": "Wraps, quesadillas, pork tacos",
      "EstimatedPrice": null,
      "Purchased": false,
      "Store": null,
      "Notes": null
    },
    {
      "ShoppingID": "SHOP011",
      "ItemID": null,
      "ItemName": "Diced tomatoes",
      "CategoryID": "CAT006",
      "QuantityNeeded": 2,
      "Unit": "cans",
      "Priority": "Low",
      "Reason": "Chili, jambalaya, casseroles",
      "EstimatedPrice": null,
      "Purchased": false,
      "Store": null,
      "Notes": null
    },
    {
      "ShoppingID": "SHOP012",
      "ItemID": null,
      "ItemName": "Cinnamon",
      "CategoryID": "CAT012",
      "QuantityNeeded": 1,
      "Unit": "jar",
      "Priority": "Medium",
      "Reason": "Pumpkin oatmeal and baking",
      "EstimatedPrice": null,
      "Purchased": false,
      "Store": null,
      "Notes": null
    }
  ],
  "mealPlan": [
    {
      "MealPlanID": "MP001",
      "Date": "2026-08-03T00:00:00",
      "Day": "Monday",
      "MealType": "Dinner",
      "RecipeID": "REC001",
      "RecipeName": "Ground Pork Fried Rice",
      "Servings": 4,
      "Completed": false,
      "Notes": null
    },
    {
      "MealPlanID": "MP002",
      "Date": "2026-08-04T00:00:00",
      "Day": "Tuesday",
      "MealType": "Dinner",
      "RecipeID": "REC004",
      "RecipeName": "Honey BBQ Pork Chops",
      "Servings": 4,
      "Completed": false,
      "Notes": null
    },
    {
      "MealPlanID": "MP003",
      "Date": "2026-08-05T00:00:00",
      "Day": "Wednesday",
      "MealType": "Dinner",
      "RecipeID": "REC003",
      "RecipeName": "Jambalaya with Ground Pork",
      "Servings": 4,
      "Completed": false,
      "Notes": null
    },
    {
      "MealPlanID": "MP004",
      "Date": "2026-08-06T00:00:00",
      "Day": "Thursday",
      "MealType": "Dinner",
      "RecipeID": "REC008",
      "RecipeName": "Tomato Soup & Garlic Toast",
      "Servings": 2,
      "Completed": false,
      "Notes": null
    },
    {
      "MealPlanID": "MP005",
      "Date": "2026-08-07T00:00:00",
      "Day": "Friday",
      "MealType": "Dinner",
      "RecipeID": "REC007",
      "RecipeName": "Garlic Toast Burgers",
      "Servings": 4,
      "Completed": false,
      "Notes": null
    },
    {
      "MealPlanID": "MP006",
      "Date": "2026-08-08T00:00:00",
      "Day": "Saturday",
      "MealType": "Snack",
      "RecipeID": "REC014",
      "RecipeName": "Peanut Butter Date Bites",
      "Servings": 4,
      "Completed": false,
      "Notes": null
    },
    {
      "MealPlanID": "MP007",
      "Date": "2026-08-09T00:00:00",
      "Day": "Sunday",
      "MealType": "Breakfast",
      "RecipeID": "REC013",
      "RecipeName": "Pumpkin Pecan Oatmeal",
      "Servings": 2,
      "Completed": false,
      "Notes": null
    }
  ]
};